### ISSUE TITLE
Drag-and-Drop Archive is outdated (includes a planned changelist)

### ISSUE THREAD

**Issue by Zorklis** [gillian-guide/gillian-guide.github.io#10]
[GTAIV.EFLC.FusionFix v2.4.1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/releases/tag/v2.4.1) released yesterday and so with new year going on, it was probably missed. Thanks for the modpack

**Comment by SandeMC** [comment]
I'm aware of the latest release, but I'm currently waiting until Characters Fixes updates to also solve crashing issues in the next update. [See this post](https://gtaforums.com/topic/927583-grand-theft-auto-iv-and-episodes-from-liberty-city-characters-fixes/?do=findComment&comment=1072321253)

I also have plans to do a bunch of changes in the next update, so hold out for that too:
- Repackage all mods that affect the `update` folder due to leftover junk.
- Completely repack Various Fixes and More Visible Interiors by using the up-to-date FFix packages from Attramet.
- Wait for the new official Characters Fixes update - then look into the FusionFix compatiblity.
- Consider Project Lights from DayL.
- Look into the crash bugs (might be fixed by the above).
- Clean off `update` from stuff FusionFix already fixes (`stipple.wtd`, `coronas.wtd` etc.)
- Considering using Console Peds from Console Visuals.
- Retire Improved Weapon Spec in favor of HiRes Misc Pack.
- Update FusionFix, Project2DFX (for CE).
- Update Radio Downgrader.
- Include FusionFix-GFWL Patch for 1.0.8.0.

**Comment by SandeMC** [comment]
The archive has been updated
